### ISSUE TITLE
Plunkr no longer works

### ISSUE THREAD

**Issue by thatchej** [austinthedeveloper/md-lightbox#2]
Hey @austinthedeveloper I just noticed that without any changes, the Plunkr no longer works. Any idea why?

**Comment by austinthedeveloper** [comment]
Check it now:

http://embed.plnkr.co/wbfUWDZQAfgVPwFtOZFC/

I'm not exactly sure how it was working in the first place... `ngMaterial` wasn't injected in the module which made it fail. I think this happened when I changed this from a directive to a self-containing module.

**Comment by thatchej** [comment]
Yeah I noticed the same thing looking at it earlier. It works great now. How was it ever working before?? That's crazy 

Regardless, thanks for figuring it out, because it actually solves the issue I was having using this in my app.
